### ISSUE TITLE
Couldn't find Version 2.3.0.0

### ISSUE THREAD

**Issue by jgarbi** [kelias/Jarloo.Sojurn#12]
Hi,
On www.jarloo.com you mention version 2.3.0.0 but I couldn't find it on GitHub. Best i got was 2.2.1.0
Did I miss something ?
Thanks for your help and your wonderful work.
best regards

**Comment by kelias** [comment]
No that is just an error on the website, I've corrected the version number there. 

I've also released as version 2.2.2.0.
