### ISSUE TITLE
TVRage provider doesn't work

### ISSUE THREAD

**Issue by eransh** [kelias/Jarloo.Sojurn#4]
The TVRage site is offline for more than ten days, if the situation isn't resolved
I suggest an alternative provider like TVMaze is in order .
A link to [TVMaze API](http://www.tvmaze.com/api)

By the way I have used your project for along time and was quite happy with it .

Eran.s

**Comment by kelias** [comment]
Thanks for adding the provider! I didn't have enough time to get to it myself.

**Comment by eransh** [comment]
You're welcome
