### ISSUE TITLE
summary of shows show html elements

### ISSUE THREAD

**Issue by edsonaf** [kelias/Jarloo.Sojurn#6]
e.g. . I used a Regular Expression to remove them in the get of the summary property. 
Another possibility might be possible, so that if a text happens to have  it can show it as bold e.g.

**Comment by kelias** [comment]
Yeah I noticed that when I added it. Figured I would get to it later. Regex was the same thing I was thinking to remove the elements. Could host a webbrowser control and inject the html so it renders too, but that would have awful performance.

**Comment by kelias** [comment]
Just pushed up code that fixes the issue.

**Comment by edsonaf** [comment]
awesome. just saw it, looks good
