### ISSUE TITLE
Sojurn 2.1.0.3 keeps crashing

### ISSUE THREAD

**Issue by jgarbi** [kelias/Jarloo.Sojurn#7]
Everytime I click on "Refresh All Shows", the application crashes.
If I refresh each show one at a time, without doing anything else, it works
If I refresh only one show and then I use the slider on that show to go further to the right, it crashes.
I follow 46 shows. 
Any ideas ?

**Comment by jgarbi** [comment]
This is the debug message I got : 
       _System.InvalidOperationException was unhandled
       Message: An unhandled exception of type 'System.InvalidOperationException' occurred in WindowsBase.dll
       Additional information: An ItemsControl is inconsistent with its items source.
       See the inner exception for more information._
Any ideas where to look ?

**Comment by kelias** [comment]
Yeah I noticed this too. I have a fix in place locally but haven't pushed it up yet as it seems more of a hack.  I'll look at it a bit more and if I don't find a better solution I'll publish what I have here.

**Comment by kelias** [comment]
Fixed now if you compile the code. I haven't released a new binary for it yet. Problem was in ImageHelper, it was doing some work on a background thread and when the UI went to read it the problem occurred.  

Also found a memory leak in there while I was at it, a filestream was opened and never explicitly closed. # #
