### ISSUE TITLE
Sojurn 2.1.0.3 keeps crashing (not solved)

### ISSUE THREAD

**Issue by jgarbi** [kelias/Jarloo.Sojurn#8]
Hi Kelias,

I downloaded the new code and compiled it just now, but I keep getting the same error as before while refreshing my shows.
Any ideas ?

Thanks

**Comment by kelias** [comment]
Mine was fixed with the last code change. Did you compile the code or download the binaries, as the binaries haven't been updated.

Also if the problem still persists could you send me your index.json file. This is located in the root folder under data. With your file I should be able to recreate the issue your experiencing.

**Comment by jgarbi** [comment]
Hi Kelias,

I downloaded the code and compiled it at the office and it crashed in the same way. I took the binaries I compiles and tried them at home and it didn't crash. But it's maybe simply because the shows had been updated by hand one by one before.
I'll keep you posted.
But here's my index.json

Thanks.


Jacques garbi     Ceo, colombus sa
+41 21 661 1675 (office)  |  +41 79 210 5076 (mobile)  |  www.colombus.com<http://www.colombus.com/>



Un service sur mesure et de qualité

**Comment by kelias** [comment]
I've released the new binaries as v2.1.0.4. If your still having issues try them.

**Comment by jgarbi** [comment]
Hi Kelias,

It just happened again. here is the error message I got on that particular PC at work :

Problem signature:
  Problem Event Name: CLR20r3
  Problem Signature 01: Jarloo.Sojurn.exe
  Problem Signature 02: 2.1.0.4
  Problem Signature 03: 58456961
  Problem Signature 04: PresentationFramework
  Problem Signature 05: 4.6.1590.0
  Problem Signature 06: 5787fd16
  Problem Signature 07: 4f66
  Problem Signature 08: 3c3
  Problem Signature 09: System.InvalidOperationException
  OS Version: 6.1.7601.2.1.0.274.10
  Locale ID: 4108
  Additional Information 1: c23a
  Additional Information 2: c23a515fc7ac60700da06ffb221190e9
  Additional Information 3: bf42
  Additional Information 4: bf4216641f90d7d0b29485815c0c3c3b

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Let me know if you need anything more.

And thanks

Take care,

Jacques garbi    Ceo, colombus sa
+41 21 661 1675 (office) | +41 79 210 5076 (mobile) | www.colombus.com<http://www.colombus.com>


Un service sur mesure et de qualité

________________________________
De : Kelly Elias [notifications@github.com]
Envoyé : mardi 6 décembre 2016 02:42
À : kelias/Jarloo.Sojurn
Cc : Jacques Garbi; Author
Objet : [SPAM] - Re: [kelias/Jarloo.Sojurn] Sojurn 2.1.0.3 keeps crashing (not solved) (#8) - Email has different SMTP TO: and MIME TO: fields in the email addresses


I've released the new binaries as v2.1.0.4. If your still having issues try them.

**Comment by kelias** [comment]
Did this get resolved with the last update? I can't seem to reproduce it. If it's still happening can you send me your index.json file? (Last one never got to me for some reason.) Can just copy the text and paste here if that is easier.

**Comment by jgarbi** [comment]
Hi Kelly,

That problem didn't happen anymore. I recompiles your code and it's been working fine so far. I don't know what happened but it seems to be fine now. I'll let you know if anything new happens.

Happy holidays. And thanks


Jacques garbi     Ceo, colombus sa
+41 21 661 1675 (office)  |  +41 79 210 5076 (mobile)  |  www.colombus.com<http://www.colombus.com/>



Un service sur mesure et de qualité

**Comment by kelias** [comment]
Thanks for the reply. I'll close this issue if you have the same issue feel free to reopen. Happy holidays for you too!

**Comment by jgarbi** [comment]
Hi Kelias,

The problem is back and has been for a little while. It's exactly as before, on at least the 2 computers I use regularly. If I don't update once a day, it crashes. And even when I do update once every day, it crashes very often.
Tell me what you need and I'll send you everything. And maybe send me your email address so I can send you the json file.

And thanks

Take care,

Jacques garbi    Ceo, colombus sa
+41 21 661 1675 (office) | +41 79 210 5076 (mobile) | www.colombus.com<http://www.colombus.com>


Un service sur mesure et de qualité

________________________________
De : Kelly Elias [notifications@github.com]
Envoyé : mardi 6 décembre 2016 02:42
À : kelias/Jarloo.Sojurn
Cc : Jacques Garbi; Author
Objet : [SPAM] - Re: [kelias/Jarloo.Sojurn] Sojurn 2.1.0.3 keeps crashing (not solved) (#8) - Email has different SMTP TO: and MIME TO: fields in the email addresses

I've released the new binaries as v2.1.0.4. If your still having issues try them.

-
